name: Github Action for LaTeX
description: GitHub Action to compile LaTeX documents
author: Cheng XU
inputs:
  texlive_version:
    description: The version of TeX Live to be used
  docker_image:
    description: The docker image to be used
  root_file:
    description: The root LaTeX file to be compiled
    required: true
  working_directory:
    description: The working directory for this action
  work_in_root_file_dir:
    description: Change directory into each root file's directory before compiling each documents
    default: "false"
  continue_on_error:
    description: Continuing to build document even with LaTeX build errors
    default: "false"
  compiler:
    description: The LaTeX engine to be invoked
    default: latexmk
  args:
    description: Extra arguments to be passed to the LaTeX engine
    default: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode"
  extra_system_packages:
    description: Install extra packages by apk
  extra_fonts:
    description: Install extra .ttf/.otf fonts.
  pre_compile:
    description: Arbitrary bash codes to be executed before compiling LaTeX documents
  post_compile:
    description: Arbitrary bash codes to be executed after compiling LaTeX documents
  latexmk_shell_escape:
    description: Instruct latexmk to enable --shell-escape
    default: "false"
  latexmk_use_lualatex:
    description: Instruct latexmk to use LuaLaTeX
    default: "false"
  latexmk_use_xelatex:
    description: Instruct latexmk to use XeLaTeX
    default: "false"

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        bash "${GITHUB_ACTION_PATH}/action.sh"
      env:
        INPUT_TEXLIVE_VERSION: ${{ inputs.texlive_version }}
        INPUT_DOCKER_IMAGE: ${{ inputs.docker_image }}
        INPUT_ROOT_FILE: ${{ inputs.root_file }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working_directory }}
        INPUT_WORK_IN_ROOT_FILE_DIR: ${{ inputs.work_in_root_file_dir }}
        INPUT_CONTINUE_ON_ERROR: ${{ inputs.continue_on_error }}
        INPUT_COMPILER: ${{ inputs.compiler }}
        INPUT_ARGS: ${{ inputs.args }}
        INPUT_EXTRA_SYSTEM_PACKAGES: ${{ inputs.extra_system_packages }}
        INPUT_EXTRA_FONTS: ${{ inputs.extra_fonts }}
        INPUT_PRE_COMPILE: ${{ inputs.pre_compile }}
        INPUT_POST_COMPILE: ${{ inputs.post_compile }}
        INPUT_LATEXMK_SHELL_ESCAPE: ${{ inputs.latexmk_shell_escape }}
        INPUT_LATEXMK_USE_LUALATEX: ${{ inputs.latexmk_use_lualatex }}
        INPUT_LATEXMK_USE_XELATEX: ${{ inputs.latexmk_use_xelatex }}

branding:
  icon: book
  color: blue
